routes/web.php
<?php

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('/home');
    }

    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/notifications', 'NotificationController@index');
Route::patch('/notifications/{id}', 'NotificationController@update');
Route::delete('/notifications', 'NotificationController@destroy');

// admin routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
    Route::resource('users', 'Admin\UserController')->except(['create', 'show', 'edit']);
    Route::resource('stores', 'Admin\StoreController')->except(['create', 'show', 'edit']);
    Route::resource('transactions', 'Admin\TransactionController')->only(['index', 'store', 'destroy']);
    Route::get('/orders', 'Admin\OrderController@index');
    Route::get('/settings', 'Admin\SettingsController@index');
    Route::post('/settings', 'Admin\SettingsController@store')->name('settings.save');
});

// store owner routes
Route::middleware(['auth', 'role:store owner', 'has_store'])
    ->prefix('owner')
    ->name('owner.')
    ->group(function () {
        Route::get('/dashboard', 'Owner\DashboardController@index');
        Route::resource('categories', 'Owner\CategoryController')->except(['create', 'edit']);
        Route::resource('products', 'Owner\ProductController')->except(['create', 'edit']);
        Route::resource('orders', 'Owner\OrderController')->only(['index', 'show', 'update']);
        Route::get('/settings', 'Owner\SettingsController@index');
        Route::post('/settings', 'Owner\SettingsController@store')->name('settings.save');
    });

// customer routes
Route::middleware(['auth', 'role:customer', 'has_profile'])->group(function () {
    Route::get('stores/{store}', 'StoreController@show');
    Route::get('products/{product}', 'ProductController@show');
    Route::get('categories/{category}', 'CategoryController@show');
    Route::get('wallet', 'WalletController@index')->name('wallet');
    Route::get('cart', 'CartController@show')->name('cart');
    Route::patch('cart', 'CartController@update')->name('cart.update');
    Route::delete('cart', 'CartController@destroy')->name('cart.empty');
    Route::resource('orders', 'OrderController')->except(['create', 'edit', 'destroy']);
    Route::get('/search', 'SearchController@index')->name('search');
});

Route::get('/settings', 'SettingsController@index');
Route::post('/settings', 'SettingsController@store')->name('settings.save');

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-12 mx-auto">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted"><i class="fa fa-cart-arrow-down"></i> Your cart</span>
                    <span class="badge badge-secondary badge-pill">{{ $cart->totalQuantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    @foreach($cart->products as $product)
                        <li class="list-group-item d-flex justify-content-between lh-condensed align-items-center">
                            <div class="flex-grow-1">
                                <h6 class="my-0 d-flex align-items-center">
                                    <a href="{{ $product->path }}" class="mr-2">{{ $product->title }}</a>
                                    <span class="badge badge-secondary">{{ $product->pivot->quantity }}</span>
                                </h6>
                                <small>{{ $product->category->store->name}}</small>
                            </div>
                            <span class="text-muted"><i class="fa fa-pound-sign"></i>
                        {{ $product->price * $product->pivot->quantity }}
                    </span>
                            <form action="{{ route('cart.update') }}" method="POST" class="mx-2">
                                @csrf
                                @method('PATCH')
                                <input type="hidden" name="remove_item">
                                <input type="hidden" name="product_id" value="{{ $product->id }}">
                                <button class="btn btn-outline-danger" type="submit"><i class="fa fa-trash"
                                                                                        aria-hidden="true"></i></button>
                            </form>
                        </li>
                    @endforeach
                    <li class="list-group-item d-flex justify-content-between">
                        <span><strong>Total</strong></span>
                        <strong><i class="fa fa-pound-sign"></i> {{ $cart->total }}</strong>
                    </li>
                </ul>
                @if($cart->products->isNotEmpty())
                    <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#cart-checkout">
                        Continue to checkout
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="cart-checkout" tabindex="-1" role="dialog"
                         aria-labelledby="modelTitleId" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Checkout</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body d-flex justify-content-center">
                                    <form action="{{ route('orders.store') }}" method="post" id="checkout-form">
                                        @csrf
                                        <input type="hidden" name="payment" id="payment-option">
                                    </form>

                                    <button class="btn btn-outline-primary btn-lg mr-1" onclick="checkout('cash')">
                                        <i class="fas fa-money-check" aria-hidden="true"></i> Pay cash
                                    </button>

                                    @if (auth()->user()->balance >= $cart->total)
                                        <button class="btn btn-outline-primary btn-lg" onclick="checkout('wallet')">
                                            <i class="fas fa-wallet"></i> Wallet (current
                                            balance: <i class="fa fa-pound-sign"></i> {{ auth()->user()->balance }})
                                        </button>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{{ route('cart.empty') }}" method="POST" id="empty-cart"
                          class="my-3 d-flex justify-content-center">
                        @csrf
                        @method('DELETE')
                        <button class="btn"
                                onclick="confirmDelete('empty-cart')">
                            <i class="fa fa-trash text-danger"></i> Empty cart
                        </button>
                    </form>
                @endif
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function confirmDelete(id) {
            event.preventDefault();
            swal({
                title: 'Are you sure?',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#' + id).submit();
                }
            });
        }

        function checkout(option) {
            switch (option) {
                case 'cash':
                    $('#payment-option').val('cash');
                    break;
                case 'wallet':
                    $('#payment-option').val('wallet');
                    break;
            }

            $('#checkout-form').submit();
        }
    </script>
@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">All stores</h1>
                <div class="list-group">
                    @foreach($stores as $store)
                        <h5><a href="{{ $store->path }}"
                               class="list-group-item font"><strong>{{ $store->name }}</strong></a></h5>
                    @endforeach
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{{ asset('images/slider-1.jpeg') }}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{{ asset('images/slider-2.jpeg') }}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{{ asset('images/slider-3.jpeg') }}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    @foreach($products as $product)
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{{ $product->path }}"><img class="card-img-top"
                                                                    src="{{ $product->image ? $product->imagePath : 'https://placehold.it/700x400' }}"
                                                                    alt=""></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{{ $product->path }}">{{ $product->title }}</a>
                                    </h4>
                                    <h5><i class="fa fa-pound-sign"></i> {{ $product->price }}</h5>
                                    <p class="card-text">{{ \Illuminate\Support\Str::words($product->description, 20) }}</p>
                                </div>
                                <div class="card-footer d-flex justify-content-between">
                                    <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9733;</span>
                                    <form action="{{ route('cart.update') }}" method="POST">
                                        @csrf
                                        @method('PATCH')
                                        <input type="hidden" name="add_item">
                                        <input type="hidden" name="product_id" value="{{ $product->id }}">
                                        <button class="btn btn-outline-success btn-sm">
                                            Add to cart
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <!-- /.row -->

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
@endsection

resources/views/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted"><i class="fa fa-search"></i>
                        Search results for: '{{ request('query') }}'
                    </span>
                </h4>
                <h6>Stores</h6>
                <ul class="list-group mb-3">
                    @foreach($stores as $store)
                    <li class="list-group-item"><a href="{{ $store->path }}">{{ $store->name }}</a></li>
                    @endforeach
                </ul>
                <h6>Categories</h6>
                <ul class="list-group mb-3">
                    @foreach($categories as $category)
                    <li class="list-group-item"><a href="{{ $category->path }}">{{ $category->name }}</a></li>
                    @endforeach
                </ul>
                <h6>Products</h6>
                <ul class="list-group mb-3">
                    @foreach($products as $product)
                    <li class="list-group-item"><a href="{{ $product->path }}">{{ $product->title }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/settings.blade.php
@extends('layouts.app')

@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800"><i class="fas fa-cogs"></i> Settings</h1>

        <div class="card-deck mb-5">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form action="{{ route('settings.save') }}" method="post" enctype="multipart/form-data">
                        @csrf

                        <legend>Update profile</legend>
                        <div class="form-group">
                            <label for="avatar">Avatar</label>
                            <input type="file" name="avatar" id="avatar" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="phone">Phone number</label>
                            <input type="text" name="phone" id="phone" class="form-control" value="{{ auth()->user()->profile->phone ?? '' }}" required>
                        </div>

                        <div class="form-group">
                            <label for="faculty">Faculty</label>
                            <input type="text" name="faculty" id="faculty" class="form-control" value="{{ auth()->user()->profile->faculty ?? '' }}">
                        </div>

                        <input type="hidden" name="update_profile">
                        <button class="btn btn-primary float-right my-3" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="card-deck">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form action="{{ route('settings.save') }}" method="post">
                        @csrf

                        <legend>Update password</legend>
                        <div class="form-group">
                            <label for="current_password">Current password</label>
                            <input type="password" name="current_password" id="current_password" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="password">New password</label>
                            <input type="password" name="password" id="password" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="password_confirmation">Confirm new password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" required>
                        </div>

                        <input type="hidden" name="update_password">
                        <button class="btn btn-primary float-right my-3" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/wallet.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-12 mx-auto my-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span><i class="fa fa-wallet"></i> My wallet balance</span>
                    <span><i class="fas fa-pound-sign"></i> {{ auth()->user()->balance }}</span>
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="table-responsive bg-white shadow-lg">
                    <table class="table table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>Transaction amount</th>
                                <th>Type</th>
                                <th>Created</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if($transactions->isNotEmpty())
                                @php $i=1 @endphp
                                @foreach($transactions as $transaction)
                                    <tr>
                                        <td scope="row">{{ $i }}</td>
                                        <td><i class="fa fa-pound-sign"
                                               aria-hidden="true"></i> {{ $transaction->amount }}</td>
                                        <td>
                                            <span class="badge badge-primary">{{ $transaction->type }}</span>
                                            @if($transaction->order)
                                                <a href="{{ $transaction->order->path }}">Order #{{ $transaction->order_id }}</a>
                                            @endif
                                        </td>
                                        <td>{{ $transaction->created_at->diffForHumans() }} by
                                            <strong>{{ $transaction->creator->name }}</strong></td>
                                    </tr>
                                    @php $i++ @endphp
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6" class="text-center">No transactions yet.</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection