routes/web.php
<?php

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('/home');
    }

    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/notifications', 'NotificationController@index');
Route::patch('/notifications/{id}', 'NotificationController@update');
Route::delete('/notifications', 'NotificationController@destroy');

// admin routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
    Route::resource('users', 'Admin\UserController')->except(['create', 'show', 'edit']);
    Route::resource('stores', 'Admin\StoreController')->except(['create', 'show', 'edit']);
    Route::resource('transactions', 'Admin\TransactionController')->only(['index', 'store', 'destroy']);
    Route::get('/orders', 'Admin\OrderController@index');
    Route::get('/settings', 'Admin\SettingsController@index');
    Route::post('/settings', 'Admin\SettingsController@store')->name('settings.save');
});

// store owner routes
Route::middleware(['auth', 'role:store owner', 'has_store'])
    ->prefix('owner')
    ->name('owner.')
    ->group(function () {
        Route::get('/dashboard', 'Owner\DashboardController@index');
        Route::resource('categories', 'Owner\CategoryController')->except(['create', 'edit']);
        Route::resource('products', 'Owner\ProductController')->except(['create', 'edit']);
        Route::resource('orders', 'Owner\OrderController')->only(['index', 'show', 'update']);
        Route::get('/settings', 'Owner\SettingsController@index');
        Route::post('/settings', 'Owner\SettingsController@store')->name('settings.save');
    });

// customer routes
Route::middleware(['auth', 'role:customer', 'has_profile'])->group(function () {
    Route::get('stores/{store}', 'StoreController@show');
    Route::get('products/{product}', 'ProductController@show');
    Route::get('categories/{category}', 'CategoryController@show');
    Route::get('wallet', 'WalletController@index')->name('wallet');
    Route::get('cart', 'CartController@show')->name('cart');
    Route::patch('cart', 'CartController@update')->name('cart.update');
    Route::delete('cart', 'CartController@destroy')->name('cart.empty');
    Route::resource('orders', 'OrderController')->except(['create', 'edit', 'destroy']);
    Route::get('/search', 'SearchController@index')->name('search');
});

Route::get('/settings', 'SettingsController@index');
Route::post('/settings', 'SettingsController@store')->name('settings.save');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800"><i class="fa fa-tachometer-alt"></i> Dashboard</h1>

        <div class="card-deck">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h4 class="card-title text-center text-primary">
                        <a href="/admin/users" class="prevent-default">Users</a>
                    </h4>
                    <p class="card-text text-center text-secondary">{{ $stats['users'] }}</p>
                </div>
            </div>
            <div class="card shadow-sm">
                <div class="card-body">
                    <h4 class="card-title text-center text-primary">
                        <a href="/admin/stores" class="prevent-default">Stores</a>
                    </h4>
                    <p class="card-text text-center text-secondary">{{ $stats['stores'] }}</p>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800"><i class="fas fa-cogs"></i> Settings</h1>

        <div class="card-deck">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form action="{{ route('admin.settings.save') }}" method="post">
                        @csrf

                        <legend>Update password</legend>
                        <div class="form-group">
                            <label for="current_password">Current password</label>
                            <input type="password" name="current_password" id="current_password" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="password">New password</label>
                            <input type="password" name="password" id="password" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="password_confirmation">Confirm new password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" required>
                        </div>

                        <button class="btn btn-primary float-right my-3" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection