routes/web.php
<?php

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('/home');
    }

    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/notifications', 'NotificationController@index');
Route::patch('/notifications/{id}', 'NotificationController@update');
Route::delete('/notifications', 'NotificationController@destroy');

// admin routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
    Route::resource('users', 'Admin\UserController')->except(['create', 'show', 'edit']);
    Route::resource('stores', 'Admin\StoreController')->except(['create', 'show', 'edit']);
    Route::resource('transactions', 'Admin\TransactionController')->only(['index', 'store', 'destroy']);
    Route::get('/orders', 'Admin\OrderController@index');
    Route::get('/settings', 'Admin\SettingsController@index');
    Route::post('/settings', 'Admin\SettingsController@store')->name('settings.save');
});

// store owner routes
Route::middleware(['auth', 'role:store owner', 'has_store'])
    ->prefix('owner')
    ->name('owner.')
    ->group(function () {
        Route::get('/dashboard', 'Owner\DashboardController@index');
        Route::resource('categories', 'Owner\CategoryController')->except(['create', 'edit']);
        Route::resource('products', 'Owner\ProductController')->except(['create', 'edit']);
        Route::resource('orders', 'Owner\OrderController')->only(['index', 'show', 'update']);
        Route::get('/settings', 'Owner\SettingsController@index');
        Route::post('/settings', 'Owner\SettingsController@store')->name('settings.save');
    });

// customer routes
Route::middleware(['auth', 'role:customer', 'has_profile'])->group(function () {
    Route::get('stores/{store}', 'StoreController@show');
    Route::get('products/{product}', 'ProductController@show');
    Route::get('categories/{category}', 'CategoryController@show');
    Route::get('wallet', 'WalletController@index')->name('wallet');
    Route::get('cart', 'CartController@show')->name('cart');
    Route::patch('cart', 'CartController@update')->name('cart.update');
    Route::delete('cart', 'CartController@destroy')->name('cart.empty');
    Route::resource('orders', 'OrderController')->except(['create', 'edit', 'destroy']);
    Route::get('/search', 'SearchController@index')->name('search');
});

Route::get('/settings', 'SettingsController@index');
Route::post('/settings', 'SettingsController@store')->name('settings.save');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    protected $appends = ['path'];
    protected $withCount = ['products'];

    /**
     * Belongs to a store.
     */
    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    /**
     * Has many products.
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    /**
     * Path.
     *
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getPathAttribute()
    {
        return url("/categories/{$this->id}");
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $category->load(['store', 'products']);

        return view('categories.show', compact('category'));
    }
}

app/Http/Controllers/Owner/CategoryController.php
<?php

namespace App\Http\Controllers\Owner;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = auth()->user()->store->categories;

        return view('owner.categories.index', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = $request->validate([
           'name' => 'required|string'
        ]);

        auth()->user()->store->categories()->create($attributes);

        return back()->with([
            'type' => 'success',
            'message' => 'Category is created successfully!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $this->authorize('view', $category);

        $category->load('products');

        return view('owner.categories.show', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);

        $attributes = $request->validate([
            'name' => 'required|string|unique:categories,id,' . $category->id,
        ]);

        $category->update($attributes);

        return back()->with([
            'type' => 'success',
            'message' => 'Category is updated successfully!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);

        $category->delete();

        return back()->with([
            'type' => 'error',
            'message' => 'Category is deleted successfully!'
        ]);
    }
}

app/Http/Controllers/Owner/DashboardController.php
<?php

namespace App\Http\Controllers\Owner;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $stats = [
            'categories' => auth()->user()->store->categories_count ?? 0,
            'products' => auth()->user()->store->products_count ?? 0
        ];

        return view('owner.dashboard', compact('stats'));
    }
}

app/Http/Controllers/Owner/OrderController.php
<?php

namespace App\Http\Controllers\Owner;

use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = auth()->user()->store->orders()->with(['customer', 'products'])->latest()->paginate(25);

        return view('owner.orders.index', compact('orders'));
    }

    public function show(Order $order)
    {
        $this->authorize('view', $order);

        $order->load(['customer', 'products']);

        return view('owner.orders.show', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $this->authorize('update', $order);

        $request->validate([
            'status' => ['required', Rule::in(['rejected', 'in progress', 'ready', 'closed'])]
        ]);

        $order->update(['status' => $request->status]);

        return back()->with([
            'Order status updated successfully!'
        ]);
    }
}

app/Http/Controllers/Owner/ProductController.php
<?php

namespace App\Http\Controllers\Owner;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = auth()->user()->store->products()->with('category')->get();
        $categories = auth()->user()->store->categories;

        return view('owner.products.index', compact('products', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = $request->validate([
            'title' => 'required|string',
            'description' => 'nullable',
            'category_id' => 'required|exists:categories,id',
            'image' => 'nullable|image|max:2048',
            'price' => 'required|numeric'
        ]);

        $category = auth()->user()->store->categories()->findOrFail($request->category_id);

        if ($request->image) {
            $attributes['image'] = $request->file('image')->store('images', 'public');
        }

        $category->products()->create($attributes);

        return back()->with([
            'type' => 'success',
            'message' => 'Product is created successfully!'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->authorize('update', $product);

        $attributes = $request->validate([
            'title' => 'required|string',
            'description' => 'nullable',
            'category_id' => 'required|exists:categories,id',
            'image' => 'nullable|image|max:2048',
            'price' => 'required|numeric'
        ]);

        $category = auth()->user()->store->categories()->findOrFail($request->category_id);

        if ($request->image) {
            $attributes['image'] = $request->file('image')->store('images', 'public');
        }

        $product->update($attributes);

        return back()->with([
            'type' => 'success',
            'message' => 'Product is updated successfully!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->authorize('delete', $product);

        $product->delete();

        return back()->with([
            'type' => 'error',
            'message' => 'Product is deleted successfully!'
        ]);
    }
}

app/Http/Controllers/Owner/SettingsController.php
<?php

namespace App\Http\Controllers\Owner;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingsController extends Controller
{
    public function index()
    {
        return view('owner.settings');
    }

    public function store(Request $request)
    {
        if ($request->has('update_password')) {
            $request->validate([
                'current_password' => 'required|string',
                'password' => 'required|string|min:6|confirmed'
            ]);

            if (! \Hash::check($request->current_password, auth()->user()->password)) {
                return back()->with([
                    'type' => 'error',
                    'message' => 'You have entered wrong password!'
                ]);
            }

            auth()->user()->updatePassword($request->password);

            return back()->with([
                'type' => 'success',
                'message' => 'Your password is updated successfully!'
            ]);
        } elseif ($request->has('update_store')) {
            $request->validate(['store' => 'required|string']);

            auth()->user()->store->update(['name' => $request->store]);

            return back()->with([
                'type' => 'success',
                'message' => 'Your store name is updated successfully!'
            ]);
        }

        return back();
    }
}

resources/views/owner/categories/index.blade.php
@extends('layouts.stores.app')

@section('content')
    <div class="container-fluid">
        <h1><i class="fa fa-database"></i> Categories
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#create-category">
                <i class="fa fa-plus-circle"></i>
            </button>

        </h1>
        <div class="modal fade" id="create-category" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Create new category</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{ route('owner.categories.store') }}" method="POST">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group row">
                                <label for="name" class="control-label col-2 align-self-center">Name</label>
                                <input type="text" class="form-control col-10" name="name" id="name"
                                       value="{{ old('name') }}" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="table-responsive bg-white shadow-lg p-3">
                    <table class="table table-hover datatable">
                        <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>Category</th>
                                <th>Created</th>
                                <th class="text-center"><i class="fa fa-cog"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if($categories->isNotEmpty())
                                @php $i=1 @endphp
                                @foreach($categories as $category)
                                    <tr>
                                        <td scope="row">{{ $i }}</td>
                                        <td><a href="/owner/categories/{{ $category->id }}">{{ $category->name }}</a></td>
                                        <td>{{ $category->created_at->diffForHumans() }}</td>
                                        <td class="d-flex align-items-center justify-content-center">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn fa fa-edit text-secondary" data-toggle="modal"
                                                    data-target="#edit-category-{{ $category->id }}">
                                            </button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="edit-category-{{ $category->id }}" tabindex="-1"
                                                 role="dialog"
                                                 aria-labelledby="modelTitleId" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Edit category '{{ $category->name }}'</h5>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <form action="{{ route('owner.categories.update', $category->id) }}"
                                                              method="POST">
                                                            @csrf
                                                            @method('PATCH')
                                                            <div class="modal-body">
                                                                <div class="form-group row">
                                                                    <label for="name"
                                                                           class="control-label col-2 align-self-center">Name</label>
                                                                    <input type="text" class="form-control col-10"
                                                                           name="name" id="name"
                                                                           value="{{ $category->name }}" required>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="submit" class="btn btn-primary">Save</button>
                                                                <button type="button" class="btn btn-secondary"
                                                                        data-dismiss="modal">Close
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                            <form action="{{ route('owner.categories.destroy', $category->id) }}" method="POST"
                                                  id="delete-category-{{ $category->id }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn"
                                                        onclick="confirmDelete('delete-category-{{ $category->id }}')">
                                                    <i class="fa fa-trash text-danger"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @php $i++ @endphp
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="4" class="text-center">No categories yet.</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function confirmDelete(id) {
            event.preventDefault();
            swal({
                title: 'Are you sure?',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#' + id).submit();
                }
            });
        }
    </script>
@endpush

resources/views/owner/categories/show.blade.php
@extends('layouts.stores.app')

@section('content')
    <div class="container-fluid">
        <h1><i class="fa fa-database"></i> {{ $category->name }}</h1>
        <div class="row">
            <div class="col-12">
                <div class="table-responsive bg-white shadow-lg p-3">
                    <table class="table table-hover datatable">
                        <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Created</th>
                                <th class="text-center"><i class="fa fa-cog"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if($category->products->isNotEmpty())
                                @php $i=1 @endphp
                                @foreach($category->products as $product)
                                    <tr>
                                        <td scope="row">{{ $i }}</td>
                                        <td><img src="{{ $product->imagePath }}" alt="{{ $product->title }}"
                                                 width="100px" height="100px" class="img-fluid img-thumbnail"></td>
                                        <td>{{ $product->title }}</td>
                                        <td><i class="fa fa-pound-sign"></i> {{ $product->price }}</td>
                                        <td>{{ $product->created_at->diffForHumans() }}</td>
                                        <td class="d-flex align-items-center justify-content-center">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn fa fa-edit text-secondary" data-toggle="modal"
                                                    data-target="#edit-category-{{ $product->id }}">
                                            </button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="edit-category-{{ $product->id }}" tabindex="-1"
                                                 role="dialog"
                                                 aria-labelledby="modelTitleId" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Edit category '{{ $product->name }}'</h5>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <form action="{{ route('owner.categories.update', $product->id) }}"
                                                              method="POST">
                                                            @csrf
                                                            @method('PATCH')
                                                            <div class="modal-body">
                                                                <div class="form-group row">
                                                                    <label for="name"
                                                                           class="control-label col-2 align-self-center">Name</label>
                                                                    <input type="text" class="form-control col-10"
                                                                           name="name" id="name"
                                                                           value="{{ $product->name }}" required>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="submit" class="btn btn-primary">Save</button>
                                                                <button type="button" class="btn btn-secondary"
                                                                        data-dismiss="modal">Close
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                            <form action="{{ route('owner.categories.destroy', $product->id) }}" method="POST"
                                                  id="delete-category-{{ $product->id }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn"
                                                        onclick="confirmDelete('delete-category-{{ $product->id }}')">
                                                    <i class="fa fa-trash text-danger"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @php $i++ @endphp
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="4" class="text-center">No products yet.</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function confirmDelete(id) {
            event.preventDefault();
            swal({
                title: 'Are you sure?',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#' + id).submit();
                }
            });
        }
    </script>
@endpush